#!/bin/bash

prepare_prettyprint_query() {
    # echo "INPUT = " $@
    # echo
    # echo \"$@\" |
    # echo $@ | sed 's/ /" -e "/g' | sed 's_^_-e _g'
    # echo tools
    for query in $@; do
        echo "-e $query "
    done

}

rga-prettyprint() {
    # echo "args=$@"
    # echo "arg1=$1"
    # echo "arg2=$2"
    QUERY="$(prepare_prettyprint_query $1)"
    # echo "QUERY=$QUERY"
    # exit
    # echo "$query"
    rga --with-filename \
        --pretty --context 5 \
        --multiline --multiline-dotall \
        $QUERY "$2"
}

file_search() {
    FILES="$(echo .)"
    for QUERY in $@; do
        # x=$(echo "$FILES" | xargs -d $'\n' cttest $QUERY)
        FILES=$(echo "$FILES" | xargs -d $'\n' rga -L --multiline --multiline-dotall --files-with-matches $QUERY)
    done
    echo "$FILES"
}

# file_search "$@"
rga-prettyprint "$@"
