#!/usr/bin/python3
from ct_tools.commons import get_isodate
from ct_tools.filestuff import open_file, fix_suffix
from pathlib import Path
import argparse
import os

DEFAULT_EXTENSION = ".md"

if __name__ == "__main__":
    import sys
    # import argparse
    # parser = argparse.ArgumentParser()

    pathstuff = None

    curr_dir = Path(".").resolve()
    if len(sys.argv) == 1:
        os.system(f"cd {get_notes_dir()} && pwd &&  rga-fzf")
    elif len(sys.argv) == 2:
        main(sys.argv[1])
