#!/usr/bin/python3
import os, sys

def make_print_args(query):
    q = ""
    for x in query.split():
        q += " -e " + x + " "
    if not q:
        q = " -e .* "
    return q

def do_regex_search(query):
    files = []
    for x in query.split():
        search_files = " ".join(["\"" + f + "\"" for f in files])
        out = os.popen(f"rga --multiline --multiline-dotall --files-with-matches {x} {search_files}").read()
        files = [f for f in out.split("\n") if f]
    return files

if __name__ == "__main__":
    cmd = sys.argv[1]
    query = sys.argv[2]
    if cmd == "make_print_args":
        print(make_print_args(query))
    elif cmd == "do_regex_search":
        results = do_regex_search(query)
        for x in results:
            print(x)
    exit(None)
