#!/bin/bash

file="$(
    FZF_DEFAULT_COMMAND="ct-rga-helper do_regex_search $1" \
        fzf --sort --preview="[[ ! -z {} ]] && ct-rga-helper print_query_hits {q} {}" \
            --phony -q "$1" \
            --bind "change:reload:ct-rga-helper do_regex_search {q}" \
            --preview-window="70%:wrap"
)" &&
echo "opening $file" &&
xdg-open "$file"
