#!/bin/bash

RGA_BASE="rga --multiline --multiline-dotall"

file="$(
    FZF_DEFAULT_COMMAND="$RGA_BASE --files-with-matches $(ct-rga-helper make_search_args '$1')" \
        fzf --sort --preview="[[ ! -z {} ]] && $RGA_BASE --pretty --context 5 \$(ct-rga-helper make_print_args {q} ) {}" \
            --phony -q "$1" \
            --bind "change:reload:$RGA_BASE --files-with-matches \$(ct-rga-helper make_search_args {q})" \
            --preview-window="70%:wrap"
)" &&
echo "opening $file" &&
xdg-open "$file"
