#!/usr/bin/python3
from ct_tools.commons import get_isodate, get_notes_dir
from ct_tools.filestuff import open_file, fix_suffix
from pathlib import Path
import argparse
import os

DEFAULT_EXTENSION = ".md"


def main(path_suffix=None):
    notes_dir = get_notes_dir()

    if path_suffix:
        f = f"{get_isodate()}-{path_suffix}"
        path = Path(notes_dir) / f
        path = fix_suffix(path, DEFAULT_EXTENSION)
        open_file(f)
    print(notes_dir)
    return notes_dir


if __name__ == "__main__":
    import sys
    # import argparse
    # parser = argparse.ArgumentParser()

    pathstuff = None

    curr_dir = Path(".").resolve()
    if len(sys.argv) == 1:
        os.system(f"cd {get_notes_dir()} && pwd &&  rga-fzf")
    elif len(sys.argv) == 2:
        main(sys.argv[1])
